import Link from 'next/link';

export const metadata = {
  title: 'CratePilot Engineering Case Study',
  description: 'How an explainable DJ-set planner combines audio DSP, transition examples, beam search, and a privacy-first local workflow.',
};

export default function CaseStudy() {
  return (
    <main className="case-shell">
      <header className="topbar">
        <Link className="brand" href="/" aria-label="CratePilot home"><span className="brand-mark">CP</span><span>CratePilot</span></Link>
        <nav aria-label="Case study navigation"><Link href="/#planner">Live demo</Link><a href="#architecture">Architecture</a><a className="nav-cta" href="https://github.com/achernet/cratepilot">Source ↗</a></nav>
      </header>
      <section className="case-hero">
        <p className="eyebrow"><span /> Engineering case study · 2026</p>
        <h1>From a folder of tracks to a set worth rehearsing.</h1>
        <p className="hero-copy">CratePilot is an explainable composition and rendering system for a first DJ performance: enough automation to escape the blank page, enough control to remain the DJ.</p>
        <div className="hero-actions"><Link className="button button-primary" href="/#planner">Operate the demo</Link><a className="button button-quiet" href="https://github.com/achernet/cratepilot">Inspect the source <span>↗</span></a></div>
      </section>

      <div className="case-main">
        <section className="case-metrics" aria-label="Project metrics"><div><strong>99</strong><span>passing workshop tests</span></div><div><strong>48</strong><span>curated transitions</span></div><div><strong>4</strong><span>recorded reference sets</span></div><div><strong>1–30</strong><span>configurable strict drafts</span></div></section>

        <section className="case-section"><div><p className="eyebrow"><span /> 01</p><h2>The problem</h2></div><div className="case-copy"><p>A music folder is not a performance. A first-time DJ still has to choose an arc, find compatible neighbors, decide where phrases meet, prepare cues, and turn the result into something Rekordbox can safely export.</p><p>The product constraint was personal and concrete: reduce the anxiety of a first booth without removing authorship. Every recommendation therefore needs a reason, every override must be respected, and the result must survive the walk from laptop to USB.</p><h3>Career context</h3><p>After a career break, I returned to hands-on engineering by turning a long-standing goal—playing my first DJ set—into an applied audio product. The work spans product design, audio analysis, optimization, DSP, security boundaries, data modeling, and release engineering.</p></div></section>

        <section className="case-section" id="architecture"><div><p className="eyebrow"><span /> 02</p><h2>Architecture</h2></div><div className="case-copy"><p>The public and private experiences share the planning language but have intentionally different trust boundaries. The website ships a sanitized fixture and no upload, provider, or acquisition route. Local mode binds to 127.0.0.1, issues a per-launch token, and validates file access against selected roots or managed storage.</p><div className="architecture"><div><b>Discover</b><span>Canonical identities merge Spotify, Shazam evidence, manual, and local sources into a bounded similarity graph.</span></div><div><b>Review</b><span>Explainable version scoring produces an explicit acquisition queue with safe source links first.</span></div><div><b>Verify</b><span>SongRec runs eleven random 12-second samples; six matching Shazam results are required before promotion.</span></div><div><b>Analyze</b><span>Librosa + FFmpeg derive tempo, Camelot key, energy, phrases, and audible bounds.</span></div><div><b>Plan</b><span>Bounded beam search returns up to 30 deterministic drafts under strict readiness constraints.</span></div><div><b>Perform</b><span>Phrase-aware DSP renders previews, a reference mix, cue notes, and a Rekordbox-safe package.</span></div><div><b>Persist</b><span>SQLite stores versioned catalog, provenance edges, jobs, smart crates, analyses, and plans.</span></div><div><b>Explain</b><span>Stable schemas expose source evidence, component scores, tempo factors, and mix notes.</span></div><div><b>Protect</b><span>Private paths, audio, provider evidence, and the learning workspace never enter public assets.</span></div></div></div></section>

        <section className="case-section"><div><p className="eyebrow"><span /> 03</p><h2>Planning</h2></div><div className="case-copy"><p>Greedy ordering made locally attractive choices that stranded the final tracks. CratePilot instead explores a bounded beam of partial sets, pruning impossible duration and ordering states while preserving several globally promising arcs.</p><div className="objective" aria-label="Planning objective weights"><span>70% transitions</span><span>20% energy</span><span>5%</span><span>5%</span></div><p>Transition compatibility blends tempo, Camelot harmony, energy, timbre, rhythm, artist spacing, and nearest examples from 48 curated transitions. Energy-curve fit encourages a confident opening, gradual rise, peak near 80%, and a controlled close. Duration and artist spacing supply smaller global corrections.</p><p>Locks and user ordering are hard constraints. A manual edit is never silently reversed: only its adjacent edges are rescored, and weak results become warnings with concrete repair options.</p></div></section>

        <section className="case-section"><div><p className="eyebrow"><span /> 04</p><h2>Rendering</h2></div><div className="case-copy"><p>The browser preview demonstrates transition geometry with lightweight Web Audio synthesis. The local renderer handles the work that matters for rehearsal: phase-aware time stretching, phrase alignment, equal-power fades, bass handoff, filter automation, loudness normalization, and true-peak limiting.</p><p>The reference master targets −14 LUFS and ≤−1 dBTP. It is a rehearsal and safety artifact, not a claim that the planned set replaces live mixing.</p><h3>Rekordbox handoff</h3><p>Export remains deliberately boring and non-destructive: sanitized numbered copies, a relative M3U8 playlist, versioned JSON, transition CSV, printable cue sheet, checksums, attribution manifest, and optional FLAC. CratePilot does not write proprietary Pioneer databases; Rekordbox remains responsible for device-library and USB export.</p></div></section>

        <section className="case-section"><div><p className="eyebrow"><span /> 05</p><h2>Tradeoffs</h2></div><div className="case-copy"><p><strong>Explainability over mystique.</strong> Example-based learning improves recommendations, but the system is not branded as an “AI DJ.” The model augments explicit DSP heuristics and exposes its contribution.</p><p><strong>Local processing over uploads.</strong> Browser-only analysis would simplify installation, but private collections are large, personal, and expensive to process. A localhost application creates a clearer privacy and performance boundary.</p><p><strong>Safe interchange over database hacks.</strong> M3U8 and documented cue notes require a verification step in Rekordbox, but they avoid coupling a first performance to unsupported database mutation.</p><p><strong>Warnings over vetoes.</strong> Compatibility is advice. The human may knowingly choose tension, surprise, or a difficult blend.</p></div></section>

        <section className="case-section"><div><p className="eyebrow"><span /> 06</p><h2>Validation</h2></div><div className="case-copy"><p>The extracted package preserves the proven transition-learning tests and adds coverage for identity collapse, bounded graph traversal, deterministic rankings, explicit approval, consensus mismatch quarantine, smart crates, strict draft diversity, schema persistence, path safety, and reproducible exports.</p><p>Recorded provider fixtures and generated beat/key audio keep personal music and live network calls out of CI. Product acceptance is equally concrete: a recruiter should discover, review, and inspect a set within 90 seconds; a first-time DJ should reach a rehearsable Rekordbox playlist without file repair.</p><Link className="text-link" href="/#discovery">Try discovery →</Link></div></section>
      </div>
      <footer><Link className="brand" href="/"><span className="brand-mark">CP</span><span>CratePilot</span></Link><p>Independent Product Engineer · Alex Chernetz · 2026—present</p><div><Link href="/#planner">Demo</Link><a href="https://github.com/achernet/cratepilot">Source</a></div></footer>
    </main>
  );
}
